### ISSUE TITLE
Publish to maven.google.com?

### ISSUE THREAD

**Issue by pocmo** [google/Accessibility-Test-Framework-for-Android#14]
In our Android projects I started to use [rules to match artifact groups to repositories](https://docs.gradle.org/current/userguide/declaring_repositories.html#sec::matching_repositories_to_dependencies) to prevent fetching potentially malicious clones from public repositories like jcenter.

I have bound most Google/Android/AndroidX artifacts to be only fetched from `maven.google.com`. However I noticed that `com.google.android.apps.common.testing.accessibility.framework:accessibility-test-framework` could no longer be resolved (as a transitive dependency of robolectric, I assume) since it it not available there (but on jcenter and maven central).

Are there any plans to release this framework on maven.google.com?

**Comment by caleb-allen** [comment]
While this is unavailable via Google's maven repository, I'm accessing this via jitpack

https://jitpack.io/#google/Accessibility-Test-Framework-for-Android/-SNAPSHOT

**Comment by anurao** [comment]
Any updates on plans to publish the latest aar. We would love to use this for our project.

**Comment by caseyburkhardt** [comment]
Update: We've published a [v3.1 artifact on `maven.google.com`](https://maven.google.com/web/index.html#com.google.android.apps.common.testing.accessibility.framework:accessibility-test-framework:3.1), which should be available now.

We will use these coordinates on Google's Maven Repository for releases going forward.

Please do advise if you encounter issues with the new artifact.

Happy Holidays,
Casey
