### ISSUE TITLE
Merge AndroidX migration PR

### ISSUE THREAD

**Issue by denyszelenchuk** [google/Accessibility-Test-Framework-for-Android#16]
Please review and merge AndroidX migration PR - https://github.com/google/Accessibility-Test-Framework-for-Android/pull/9

**Comment by caseyburkhardt** [comment]
Sincerest apologies on the delay here. We believe this to be resolved in our latest v3.1 release, which has just been merged into master. Please advise if you think something was missed. You can expect binaries on maven in the coming days.
