### ISSUE TITLE
Use of Accessibility Test Framework

### ISSUE THREAD

**Issue by deep-mm** [google/Accessibility-Test-Framework-for-Android#20]
How do I run this for an apk of the app that I have created in some other language?
Can you mention the steps as to how to implement this project

**Comment by tobecrazy** [comment]
I think you can use gradle package it , finally you can get aar file and import to your project

**Comment by caseyburkhardt** [comment]
That's correct -- you can create an aar with the provided gradle build and wrapper to import into your project.  We are also in the process of pushing prebuilt artifacts to maven, which you will then be able to depend upon directly.  If you'd like more updates on that, I'd suggest following issue #14   We are planning to first push an update to our existing artifact collection in Maven Central, and will then spin up artifacts on maven.google.com
