### ISSUE TITLE
When is the planned 3.1 release?

### ISSUE THREAD

**Issue by sunyal** [google/Accessibility-Test-Framework-for-Android#21]
I see that 2.1 is the last release to the Maven repositories, but that was December 2015. When is the next release to the Maven repos?

**Comment by tobecrazy** [comment]
Is this project still under maintains ? I really doubt it

**Comment by BradleyWire** [comment]
Do we have an update on this?

**Comment by sunyal** [comment]
@caseyburkhardt I see that the latest commits have fixed the repository allowing it to be built locally. Are you planning on releasing it to the Maven repos?

**Comment by caseyburkhardt** [comment]
We definitely appreciate your patience, and realize it's taken much longer than it should to push the v3.1 binary. As a matter of practice, we don't provide specific commitments for release timeframes.

We have made some adjustments to our release process, and will be migrating to `maven.google.com` with this release.  The binary is staged, and testing/review is underway.  We expect to have an update soon, and are aiming for a faster release cadence going forward.

**Comment by sunyal** [comment]
Thank you @caseyburkhardt for the information

**Comment by caseyburkhardt** [comment]
Update: We've published a [v3.1 artifact on `maven.google.com`](https://maven.google.com/web/index.html#com.google.android.apps.common.testing.accessibility.framework:accessibility-test-framework:3.1), which should be available now.

We will use these coordinates on Google's Maven Repository for releases going forward.

Please do advise if you encounter issues with the new artifact.

Happy Holidays,
Casey
