### ISSUE TITLE
TouchTargetSizeCheck should keep padding into account as well.

### ISSUE THREAD

**Issue by jkaan** [google/Accessibility-Test-Framework-for-Android#35]
This might be a naive question/statement but at first glance it does make sense to me.

I'm curious why the `TouchTargetSizeCheck` doesn't take into account padding of the view, I feel that it should since this would also enlarge the tap area of a view.

**Comment by oknirb** [comment]
TouchTargetSizeCheck uses the visible bounds of a view within the screen, as reported by [View.getGlobalVisibleRect](https://developer.android.com/reference/android/view/View#getGlobalVisibleRect(android.graphics.Rect)) or [AccessibilityNodeInfo.getBoundsInScreen](https://developer.android.com/reference/android/view/accessibility/AccessibilityNodeInfo#getBoundsInScreen(android.graphics.Rect)), depending on its environment. Normally these should match the touch target. However, some Views may deviate from this behavior in a custom OnTouchListener.

**Comment by jkaan** [comment]
Makes total sense! Thanks for the clarification :)
