### ISSUE TITLE
Is this project end of life?

### ISSUE THREAD

**Issue by bootstraponline** [google/Accessibility-Test-Framework-for-Android#6]
Is this project end of life? I don't see any new commits. PRs sit unmerged for years.

**Comment by manoj9788** [comment]
@pweaver-google

**Comment by byzhnyawrzad** [comment]
Sms

**Comment by bootstraponline** [comment]
@pweaver-google Is this project end of life? 😭

**Comment by caseyburkhardt** [comment]
No, the project is not end-of-life.  Stay tuned for a project update in the coming weeks!

**Comment by manoj9788** [comment]
That's good news thanks @caseyburkhardt
